// import { BookStatus, DocumentStatus } from 'src/utils/types';

// export const BooksSeed = [
//   // {
//   //   name: 'Tôi thấy hoa vàng trên cỏ xanh',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df2'],
//   // },
//   // {
//   //   name: 'Đôi mắt',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Văn học'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 50000,
//   //   priceUnDiscount: 90000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df2'],
//   // },
//   // {
//   //   name: 'Đời thừa',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 20000,
//   //   priceUnDiscount: 90000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df0', '625a89ce96200f1ddd041def'],
//   // },
//   // {
//   //   name: 'Sống đẹp',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Thời sự'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 80000,
//   //   priceUnDiscount: 100000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df2'],
//   // },
//   // {
//   //   name: 'Chí Phèo',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df3', '625a89ce96200f1ddd041df6'],
//   // },
//   // {
//   //   name: 'Chiếc lược ngà',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Chiến tranh', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df5', '625a89ce96200f1ddd041df6'],
//   // },
//   // {
//   //   name: 'Những ngôi sao xa xôi',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Chiến tranh'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 100000,
//   //   priceUnDiscount: 140000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df4', '625a89ce96200f1ddd041df3'],
//   // },
//   // {
//   //   name: 'Hoa mai',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 5000,
//   //   priceUnDiscount: 15000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041def', '625a89ce96200f1ddd041df3'],
//   // },
//   // {
//   //   name: 'Đôi mắt 1',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '6231ed074793ecd4a7780516'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041dee', '625a89ce96200f1ddd041df0'],
//   // },
//   // {
//   //   name: 'Đôi mắt 2',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['625a89ce96200f1ddd041def', '625a89ce96200f1ddd041df2'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df0', '625a89ce96200f1ddd041df2'],
//   // },
//   // {
//   //   name: 'Đôi mắt 3',
//   //   author: 'Nam Cao',
//   //   cloudTag: ['Truyện ngắn', 'Tình yêu'],
//   //   description: 'Truyên kể về 1 mối tình buồn lắm',
//   //   price: 30000,
//   //   priceUnDiscount: 40000,
//   //   thumbnail:
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //   category: ['6231ed074793ecd4a7780516', '625a89ce96200f1ddd041df2'],
//   //   status: BookStatus.HOT,
//   //   images: [
//   //     'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//   //     'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//   //     'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//   //     'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//   //   ],
//   //   quantity: 100,
//   //   documentStatus: DocumentStatus.Approved,
//   //   summary:
//   //     '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//   //   publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
//   // },
//   {
//     name: 'Combo 1',
//     author: 'Nam Cao',
//     cloudTag: ['Truyện ngắn', 'Tình yêu'],
//     description: 'Truyên kể về 1 mối tình buồn lắm',
//     price: 30000,
//     priceUnDiscount: 40000,
//     thumbnail:
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//     category: ['6231ed074793ecd4a7780516', '625a89ce96200f1ddd041df2'],
//     status: BookStatus.HOT,
//     images: [
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//       'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//       'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//       'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//     ],
//     quantity: 100,
//     documentStatus: DocumentStatus.Approved,
//     summary:
//       '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//     publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
//     isCombo: true,
//     books: ['625a8bc7cc75e5350bacb7bf', '625a8bc7cc75e5350bacb7bd'],
//   },
//   {
//     name: 'Combo 2',
//     author: 'Nam Cao',
//     cloudTag: ['Truyện ngắn', 'Tình yêu'],
//     description: 'Truyên kể về 1 mối tình buồn lắm',
//     price: 30000,
//     priceUnDiscount: 40000,
//     thumbnail:
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//     category: ['6231ed074793ecd4a7780516', '625a89ce96200f1ddd041df2'],
//     status: BookStatus.HOT,
//     images: [
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//       'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//       'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//       'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//     ],
//     quantity: 100,
//     documentStatus: DocumentStatus.Approved,
//     summary:
//       '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//     publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
//     isCombo: true,
//     books: [
//       '625a8bc7cc75e5350bacb7c0',
//       '625a8bc7cc75e5350bacb7be',
//       '625a8bc7cc75e5350bacb7c1',
//     ],
//   },
//   {
//     name: 'Combo 3',
//     author: 'Nam Cao',
//     cloudTag: ['Truyện ngắn', 'Tình yêu'],
//     description: 'Truyên kể về 1 mối tình buồn lắm',
//     price: 30000,
//     priceUnDiscount: 40000,
//     thumbnail:
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//     category: ['6231ed074793ecd4a7780516', '625a89ce96200f1ddd041df2'],
//     status: BookStatus.HOT,
//     images: [
//       'https://i.pinimg.com/originals/4b/f1/93/4bf19336b3b9c9955e86e251d5008adf.jpg',
//       'http://image.vtc.vn/files/f1/2015/10/02/phimtijcjpg.jpg',
//       'https://thoibaonganhang.vn/stores/news_dataimages/thanhlm/092016/26/09/507f53fd797827147d29272b919e8a8b_Untitled.jpg',
//       'https://sanvemaybay.vn/includes/uploads/2017/04/hoavangcoxanh.jpg',
//     ],
//     quantity: 100,
//     documentStatus: DocumentStatus.Approved,
//     summary:
//       '<p>Xin chao cac ban. Day la tom tat co ban cua <strong>Toi thay hoa vang tren co xanh</strong></p>',
//     publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
//     isCombo: true,
//     books: ['625a8bc7cc75e5350bacb7c4', '625a8bc7cc75e5350bacb7be'],
//   },
// ];

export const BooksSeed = [
  {
    name: 'Sách Người trong muôn nghề',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'Hầu hết những người trẻ đều đã từng hoặc đang trải qua cảm giác không biết mình thuộc về đâu. Khó khăn lớn nhất có lẽ không phải là kiếm được việc, mà là chọn được một nghề thực sự phù hợp với bản thâ...',
    price: 169000,
    priceUnDiscount: 172000,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/58/89/8f/735764c5e6d8816a408e934ef2435a2c.png',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/58/89/8f/735764c5e6d8816a408e934ef2435a2c.png',
      'https://salt.tikicdn.com/ts/product/40/85/88/703b8d979028fe282cd4144bd9db9c2c.png',
      'https://salt.tikicdn.com/ts/product/b0/cd/45/39ec10f4d7441d685cc8be56e453c862.png',
      'https://salt.tikicdn.com/ts/product/08/44/c3/9a7a00a67fedbf051a8f6d68622990bb.png',
      'https://salt.tikicdn.com/ts/product/97/b8/0f/758fcf2e4a25284c362492c6a1c601f6.jpg',
    ],
    quantity: 100,
    summary:
      '<p>Hầu hết những người trẻ đều đã từng hoặc đang trải qua cảm giác không biết mình thuộc về đâu. Khó khăn lớn nhất có lẽ không phải là kiếm được việc, mà là chọn được một nghề thực sự phù hợp với bản thân. Trên hành trình kiếm tìm ấy, người trẻ phải gánh trên vai rất nhiều áp lực vô hình từ gia đình và xã hội. Đi học thì ngành phải "hot", trường phải "xịn". Đi làm thì vị trí phải “oai", lương tháng phải “cao", công ty phải “khủng". </p>\n<p>Chúng ta mải chạy theo những thứ bề nổi mà quên mất rằng mục đích sau cùng của việc chọn ngành, chọn nghề là giúp mình tìm được điểm giao thoa giữa năng lực, sở thích cá nhân với nhu cầu của xã hội.</p>\n<p><strong>Người Trong Muôn Nghề</strong> hi vọng có thể kéo bạn lại gần hơn với mục đích bản chất ấy. Cuốn sách là tuyển tập những câu chuyện đi làm tâm huyết đến từ những cây viết dày dặn kinh nghiệm trong các lĩnh vực chuyên môn và những môi trường làm việc khác nhau. Những chia sẻ này sẽ giúp các bạn học sinh, sinh viên có một cái nhìn toàn diện hơn về thế giới công việc thực thụ: </p>\n<div><em>- Làm việc tại tập đoàn lớn thì khác gì với môi trường startup, nhà nước, và freelance? </em></div>\n<div><em>- Làm thế nào để có được một tư duy đúng đắn trong việc lựa chọn nghề nghiệp, và cần chuẩn bị những gì từ khi còn ngồi trên ghế nhà trường? </em></div>\n<div><em>- Đâu là những điểm đặc thù của mỗi ngành nghề – từ Công nghệ thông tin, Kỹ thuật, Kiểm toán cho tới Giáo dục, Y tế, Marketing, thậm chí là những nghề rất mới như làm Game, làm Youtube?</em> </div>\n<div> </div>\n<div>Xuyên suốt cuốn sách này, các bạn có thể thu thập thêm những thông tin hữu ích cũng như gia tăng thêm các cơ hội việc làm thông qua việc scan các QR code ở cuối mỗi chương. </div>\n<div> </div>\n<div>Bạn không bắt buộc phải chọn “đúng" một công việc và làm điều đó cả đời, bởi vì mỗi người luôn có thể học được điều gì đó từ những lựa chọn sai lầm. Thế nhưng bạn luôn có thể mài sắc khả năng học hỏi của bản thân để thích nghi và sẵn sàng cho một thế giới việc làm luôn không ngừng thay đổi. Hi vọng <strong>Người Trong Muôn Nghề</strong> có thể đồng hành cùng bạn trên chặng đường này. </div>\n<div> </div><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách - Hành Trình Về Phương Đông (Bìa Mềm - Tái bản 2021) - First News',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      '       Nhà xuất bản: NXB Thế Giới   Tác giả: Baird T. Spalding   Phóng tác: Nguyên Phong   Năm xuất bản: 2021   Kích thước 14,5 x 20.5 cm   Loại bìa: Bìa mềm   Số trang: 151   Giá bìa: 118....',
    price: 100300,
    priceUnDiscount: 103300,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/25/5a/d4/fc46af47ce7a83545a7f5c1344d260b7.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/25/5a/d4/fc46af47ce7a83545a7f5c1344d260b7.jpg',
      'https://salt.tikicdn.com/ts/product/2b/a9/0f/b99d7a7a5873ea8909c1a0786694bfd0.jpg',
      'https://salt.tikicdn.com/ts/product/82/56/08/fa10f54ad6f6d57ec72c459897557bd3.jpg',
      'https://salt.tikicdn.com/ts/product/af/24/92/dc38268a6cf3c1523a7bea8ce0420f33.jpg',
      'https://salt.tikicdn.com/ts/product/c1/b8/fa/95f13b159c4854ead92cef703dbb59fc.jpg',
      'https://salt.tikicdn.com/ts/product/c5/30/4f/1393077cc120f856dec9fbfec1beaaf5.jpg',
    ],
    quantity: 100,
    summary:
      '<html>\n <head></head>\n <body>\n  <ul>\n   <p>Nhà xuất bản: NXB Thế Giới</p>\n   <p>Tác giả: Baird T. Spalding</p>\n   <p>Phóng tác: Nguyên Phong</p>\n   <p>Năm xuất bản: 2021</p>\n   <p>Kích thước 14,5 x 20.5 cm</p>\n   <p>Loại bìa: Bìa mềm</p>\n   <p>Số trang: 151</p>\n   <p>Giá bìa: 118.000 VNĐ</p>\n   <p>Mô tả sản phẩm:</p>\n   <p>HÀNH TRÌNH VỀ PHƯƠNG ĐÔNG.</p>\n   <p>Một trong những tác phẩm đương đại độc đáo nhất về văn hoá phương Đông. Hành trình về phương Đông kể về những trải nghiệm của một đoàn khoa học gồm các chuyên gia hàng đầu của Hội Khoa Học Hoàng Gia Anh được cử sang Ấn Độ nghiên cứu về huyền học và những khả năng siêu nhiên của con người. Suốt hai năm trời rong ruổi khắp các đền chùa Ấn Độ, chúng kiến nhiều pháp luật, nhiều cảnh mê tín dị đoan, thậm chí lừa đảủa nhiều pháp sư, đạo sĩọ được tiếp xúc với những vị thế, họ được chứng kiến, trải nghiệm, hiểu biết sâu sắc về các khoa học cổ xưa và bí truyền của văn hóa Ấn Độ như Yoga, thiền định, thuật chiêm duyên, nghiệp báo, luật nhân quả, cõi sống và cõi chế</p>\n   <p>Đúng lúc một cuộc đối thoại cởi mở và chân thành đang sắp diễn ra với các đạo sĩ bậc thầy, thì đoàn nhận được tối hậu thư từ chính quyền Anh Quốc là phải ngừng ngay việc nghiên cứu, tức khắc hồi hương và bị buộc phải im lặng, không được phát ngôn về bất cứ điều gì mà họ đã chứng nghiệm. Sau cùng ba nhà khoa học trong đoàn đã chấp nhận bỏ lại tất cả sau lưng, ở lại Ấn Độ tiếp tục nghiên cứu và cuối cùng trở thành tu sĩ. Trong số đó có giáo sư Spalding - tác giả hồi ký đặc biệt này.</p>\n   <p>Hành trình về phương Đông - thông qua ngòi bút của dịch giả Nguyên phong - giúp người đọc đến gần với những nét văn hoá của phương Đông, khám phá các giá trị vình hằng của cuộc sống. Tác phẩm luôn nằm trong top 10 cuốn sách bán chạy nhất của First News, được đánh giá là một trong những cuốn sách đương đại độc đáo, khác biệt nhất về phương Đông.</p>\n  </ul>\n </body>\n</html><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Bộ Sách Nhỏ Về Tâm Lý: Tâm Lý Học Nói Gì Về Hạnh Phúc',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'Tâm lý học nói gì về Hạnh phúc?Liệu có phải hạnh phúc hoàn toàn phụ thuộc vào may mắn? Những sự kiện trong đời có ảnh hưởng đến mức độ hạnh phúc của ta? Quá nhiều một thứ tốt đẹp liệu có khiến ta bớt...',
    price: 81700,
    priceUnDiscount: 84700,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/59/e3/e7/642ce38017ac1d35f2e87234b6fd56f2.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/59/e3/e7/642ce38017ac1d35f2e87234b6fd56f2.jpg',
    ],
    quantity: 100,
    summary:
      'Tâm lý học nói gì về Hạnh phúc?<br />\nLiệu có phải hạnh phúc hoàn toàn phụ thuộc vào may mắn? Những sự kiện trong đời có ảnh hưởng đến mức độ hạnh phúc của ta? Quá nhiều một thứ tốt đẹp liệu có khiến ta bớt hạnh phúc đi không?<br />\n“Tâm lý học nói gì về hạnh phúc?” sẽ giới thiệu cho độc giả vô vàn những yếu tố có thể ảnh hưởng đến mức độ hạnh phúc. Từ tính cách và sự tự tin về giá trị bản thân, cho đến sức khỏe thể chất và tình trạng công việc, hạnh phúc là trải nghiệm chủ quan và sẽ thay đổi trong suốt cuộc đời. Cảm giác hạnh phúc được gắn liền với suy nghĩ tích cực và sự quảng giao trong đời sống hằng ngày, nhưng cuốn sách cũng sẽ đề cập đến những sự thật đầy bất ngờ về mặt hạn chế của hạnh phúc cá nhân.<br />\nAi cũng muốn cảm thấy hạnh phúc trong đời. Cuốn sách nhỏ này sẽ giúp bạn hiểu rõ về hạnh phúc, đối phó với bất hạnh và cải thiện hạnh phúc theo phương cách riêng của tâm lý học.<br /><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ ( Những Thay Đổi Nhỏ Tạo Nên Thành Công Lớn/ Tặng kèm Bookmark)',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      "Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ•  Wall Street Journal Bestseller, USA Today Bestseller, Publisher's Weekly Bestseller•  Nằm trong Top 20 tựa sách thể loại non-fiction bán chạy và đư...",
    price: 186350,
    priceUnDiscount: 189350,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/e2/32/b3/085ee546b06b792e847edd88b02b8f15.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/e2/32/b3/085ee546b06b792e847edd88b02b8f15.jpg',
    ],
    quantity: 100,
    summary:
      "<p><strong>Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ</strong></p>\n<p><em><strong>•  Wall Street Journal Bestseller, USA Today Bestseller, Publisher's Weekly Bestseller<br />•  Nằm trong Top 20 tựa sách thể loại non-fiction bán chạy và được tìm đọc nhiều nhất của Amazon suốt 40 tuần tính đến tháng 9/2019</strong></em></p>\n<p>Một thay đổi tí hon có thể biến đổi cuộc đời bạn không?</p>\n<p>Hẳn là khó đồng ý với điều đó. Nhưng nếu bạn thay đổi thêm một chút? Một chút nữa? Rồi thêm một chút nữa? Đến một lúc nào đó, bạn phải công nhận rằng cuộc sống của mình đã chuyển biến nhờ vào một thay đổi nhỏ</p>\n<p>Và đó chính là sức mạnh của thói quen nguyên tử.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>",
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách: Hài Hước Một Chút Thế Giới Sẽ Khác Đi (Tái Bản)',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'Hài Hước Một Chút Thế Giới Sẽ Khác Đi Trong xã hội hiện đại, giao tiếp là chìa khóa giải quyết mọi vấn đề. Vậy làm thế nào để giao tiếp hiệu quả? Đó là biết vận dụng một cách tinh tế sự hài hước vào...',
    price: 60000,
    priceUnDiscount: 63000,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/e6/2b/2c/eb59f9f0496bda757fead238bd07e3a8.png',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/e6/2b/2c/eb59f9f0496bda757fead238bd07e3a8.png',
      'https://salt.tikicdn.com/ts/product/2b/87/88/1e12c5924b455a5c60cd5156ec9f12ac.jpg',
      'https://salt.tikicdn.com/ts/product/bf/53/ab/65b1b52ba8b4dca467e92120320c1654.jpg',
      'https://salt.tikicdn.com/ts/product/72/f4/5d/b87e48ec34f93cae67f886453ec47ed0.jpg',
    ],
    quantity: 100,
    summary:
      '<h1 style="text-align: justify;"><strong>Hài Hước Một Chút Thế Giới Sẽ Khác Đi</strong></h1>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;"><em><strong>Trong xã hội hiện đại, giao tiếp là chìa khóa giải quyết mọi vấn đề. Vậy làm thế nào để giao tiếp hiệu quả? Đó là biết vận dụng một cách tinh tế sự hài hước vào lời nói và tư duy, hài hước có thể giúp giúp chúng ta thiết lập được mạng lưới quan hệ rộng rãi. Tuy nhiên, hài hước không phải là một năng lực bẩm sinh, muốn có được “nghệ thuật giúp bạn thành công” này, bạn phải trải qua quá tình bồi dưỡng và rèn luyện bản thân.</strong></em></p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;"><em><strong>Hài hước một chút, thế giới sẽ khác đi</strong> - cuốn sách với nội dung phong phú mà sâu sắc này sẽ giúp các bạn có được cái nhìn rõ nét hơn về tính hài hước dưới các góc độ, phương diện đánh giá khác nhau, cũng như có thêm kĩ năng vận dụng sự hài hước vào cuộc sống hàng ngày.</em></p>\n<p style="text-align: justify;"> </p>\n<p><em><img class="ckimgrsz" style="display: block; margin-left: auto; margin-right: auto;" src="https://salt.tikicdn.com/ts/product/1a/6e/ca/c01cc5088baae02b0d3bcc1e89d5c6a9.jpg" width="600" height="429" data-cke-saved-src="https://salt.tikicdn.com/ts/product/1a/6e/ca/c01cc5088baae02b0d3bcc1e89d5c6a9.jpg" /></em></p>\n<p> </p>\n<h2 style="text-align: justify;"><strong>Làm thế nào để trở thành người tài giỏi hài hước?</strong></h2>\n<p style="text-align: justify;">Hài hước là vận dụng những ngôn từ thông minh, thú vị để tiết lộ, phê bình hay giễu cợt một cách hàm súc những sự vật, hiện tượng không hợp lí, những mâu thuẫn trong đời sống xã hội, khiến người ta phủ định sự vật hay hiện tượng trong những tiếng cười thoải mái, nhẹ nhàng. Nhưng hài hước không phải là muốn nói thế nào cũng được, cuốn sách <em>Hài hước một chút thé giới sẽ khác đi</em> đưa ra 10 nguyên tắc cơ bản để trở thành người người tài giỏi hài hước:</p>\n<p style="text-align: justify;">1. Có một tâm lí lành mạnh, lạc quan, tích cực</p>\n<p style="text-align: justify;">2. Nhìn nhận thế giới từ góc độ thú vị</p>\n<p style="text-align: justify;">3. Trí nhớ và khả năng phản ứng tốt</p>\n<p style="text-align: justify;">4. Lùi một bước để tiến hai bước, biết nhường nhịn người khác</p>\n<p style="text-align: justify;">5. Hiểu rõ “liều lượng” của hài hước</p>\n<p style="text-align: justify;">6. Tôn trọng là tiền đề của hài hươc</p>\n<p style="text-align: justify;">7. Có một trái tim ngây thơ, hồn nhiên</p>\n<p style="text-align: justify;">8. Nói một cách uyển chuyển, tế nhị</p>\n<p style="text-align: justify;">9. Vòng vo một chút, hiệu quả sẽ tốt hơn</p>\n<p style="text-align: justify;">10. Trí tuệ được cộng điểm nhờ sự hài hước</p>\n<p style="text-align: justify;"><br />Không đơn thuần chỉ đưa ra những quy luật khái quát cho người tập tành khiếu hài hước, Hài hước một chút thế giới sẽ khác đi còn đưa ra những bí quyết đinh áp dụng vào từng mối quan hệ cụ thể trong cuộc sống.</p>\n<p style="text-align: justify;"> </p>\n<h2 style="text-align: justify;"><strong>Nghệ thuật hài hước trong cuộc sống gia đình</strong></h2>\n<p> </p>\n<p style="text-align: justify;">Phần đông mọi người nhận định trong cuộc sống gia đình chỉ cần chuyện trò thoải mái, vợ chồng phải nói chyện một cách thực tế, không cần chú trọng vào nghệ thuật nói chuyện. Nhưng họ không biết rằng sự dí dỏm có thể hóa giải được rất nhiều mâu thuẫn và tranh cãi vợ chồng, giải tỏa những hiểu nhầm, bất đồng, xóa nhòa khoảng cách, thắt chặt tình cảm để cả gia đình sống trong không khí đầm ấm. </p>\n<p style="text-align: justify;"> </p>\n<p><img class="ckimgrsz" style="display: block; margin-left: auto; margin-right: auto;" src="https://salt.tikicdn.com/ts/product/f6/9d/37/dedd11be84683d4d0db8425c6ff94921.jpg" width="600" height="429" data-cke-saved-src="https://salt.tikicdn.com/ts/product/f6/9d/37/dedd11be84683d4d0db8425c6ff94921.jpg" /></p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;">Lưu Chấn Hồng trong <strong><em>Hài hước một chút thế giới sẽ khác đi</em></strong> cho rằng hài hước chính là gia vị của hôn nhân, tạo ra sự bình đảng trong quan hệ vợ chồng. Bởi vậy, trong giao tiếp trong gia đình, nên dùng sự hài hước khéo léo trách cứ để không gây tổn thương, khéo léo khen ngợi để không gây tự mãn, Nhờ vậy, hài hước chắc chắn sẽ là nhân tố vun đắp cuộc sống hôn nhân bền lâu.</p>\n<p style="text-align: justify;"> </p>\n<h2 style="text-align: justify;"><strong>Hài hước trong giao tiếp xã hội</strong></h2>\n<p style="text-align: justify;">Muốn mở rộng các mối quan hệ một cách thuận lợi thì sự hài hước là một điều cần thiết. Một người muốn xây dựng các mối quan hệ của mình thì việc phải giao tiếp với người khác là điều đương nhiên. Vào lúc này, hài hước chính là phương pháp giao tiếp tốt nhất.</p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;">Trong giao tiếp xã hội, hài hước là thiên sứ vui vẻ kết nối tâm hồn mọi người với nhau, có hài hước thì sẽ có tình yêu và tình bạn. Người hài hước đi đến đâu thì nơi ấy sẽ có được không khí hòa thuận, vui vẻ.</p>\n<p style="text-align: justify;"> </p>\n<h2 style="text-align: justify;"><strong>Hài hước trong công việc</strong></h2>\n<p style="text-align: justify;">Hài hước là một biểu hiện của sự tự tin, phản ánh tố chất khéo léo xử lí quan hệ giao tiếp của mỗi người. Bởi vậy, không lạ khi giờ đây, đây là một trong những yếu tố chìa khóa để nhà tuyển dụng quyết định quyết định công việc của các ứng viên, hay quản lý đánh giá năng lực của nhân viên trong công ty. </p>\n<p style="text-align: justify;"> </p>\n<p><img class="ckimgrsz" style="display: block; margin-left: auto; margin-right: auto;" src="https://salt.tikicdn.com/ts/product/53/7c/ad/8b24df3816bd88e2ef8b2f40be6581d2.jpg" width="600" height="429" data-cke-saved-src="https://salt.tikicdn.com/ts/product/53/7c/ad/8b24df3816bd88e2ef8b2f40be6581d2.jpg" /></p>\n<p style="text-align: justify;">Vậy thế nào để hài hước đạt hiệu quả nơi công sở? Hài hước một chút thế giới sẽ khác đi sẽ cho bạn câu trả lời trong từng tình huống cụ thể sau đây: Dùng sự hài hước để có được thiện cảm của cấp dưới, dùng sự hài hước để đổi lại thái độ thân thiện của đồng nghiệp, dùng sự hài hước để xoa dịu áp lực công việc hay để đàm phán thuyết phục khách hàng.</p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;">Tóm lại, biết cách hài hước đúng mực sẽ giúp bạn thành công. Hi vọng rằng sau khi đọc xong cuốn sách Hài hước một chút thế giới sẽ khác đi, bạn có thể biến mình thành một người biết nói chuyện, khéo lẹo vận dụng những ngôn từ hài hước, “gãi đúng chỗ ngứa” của đối phương để được mọi người yêu mến.</p>\n<p style="text-align: justify;"><iframe src="//www.youtube.com/embed/jsKuz07cfrg" width="560" height="314" allowfullscreen="allowfullscreen"></iframe></p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;"> </p>\n<p style="text-align: justify;"> </p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách The Magic - Phép Màu (Rhonda Byrne)',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'SÁCH THE MAGIC PHÉP MÀU (RHONDA BYRNE)Con đường dễ nhất, nhanh nhất giúp thay đổi cuộc sống của bạn.Nội dung bên trong sách The Magic - Phép màuTrải qua hơn 20 thế kỷ, hàm ý của nhiều ngôn từ giá ...',
    price: 158000,
    priceUnDiscount: 161000,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/09/ba/f3/bc4eb7938152765e38405a10f1e18830.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/09/ba/f3/bc4eb7938152765e38405a10f1e18830.jpg',
      'https://salt.tikicdn.com/ts/product/bf/43/33/e2f6849b6f037d2188d95e87977d1916.jpg',
      'https://salt.tikicdn.com/ts/product/60/74/99/daf56d20c1dc599e0de9b0755692128b.jpg',
      'https://salt.tikicdn.com/ts/product/ef/8f/3a/6816beb4505f2f40866eda93689c3ed8.jpg',
      'https://salt.tikicdn.com/ts/product/a1/24/00/274294d351d9013107a05276853589c8.jpeg',
      'https://salt.tikicdn.com/ts/product/e3/df/9f/61a338483f6d487ae9e226b76d04b9be.jpeg',
    ],
    quantity: 100,
    summary:
      '<p><strong>SÁCH THE MAGIC PHÉP MÀU (RHONDA BYRNE)</strong></p>\n<p>Con đường dễ nhất, nhanh nhất giúp thay đổi cuộc sống của bạn.</p>\n<p><img src="https://salt.tikicdn.com/ts/tmp/ef/8f/3a/f255801fe68ddff2a83e284852fbd91c.jpg" alt="" width="750" height="562"></p>\n<p style="text-align:center;"><em>Nội dung bên trong sách The Magic - Phép màu</em></p>\n<p>Trải qua hơn 20 thế kỷ, hàm ý của nhiều ngôn từ giá trị đã bị thất lạc, gây ra khó hiểu và đôi khi bị hiểu sai bởi những người đọc nó. Có những vấn đề quan trọng được giải quyết ở bên trong mỗi từ ngữ, những ẩn ý phải được làm sáng tỏ – và khi bạn hiểu được ý nghĩa thực sự của ngôn từ, một thế giới hoàn toàn mới sẽ mở ra trước mắt bạn.</p>\n<p>Trong cuốn sách The Magic Phép Màu, Rhonda Byrne đã tiết lộ một kiến thức thay đổi cuộc sống về sức mạnh của lòng biết ơn ẩn chứa trong một lời dạy cổ linh thiêng được truyền dạy cách đây hơn 2000 năm. Từ đó, trong hành trình ngạc nhiên xuyên suốt 28 ngày này, Rhonda Byrne sẽ hướng dẫn bạn cách thức áp dụng kiến thức thay đổi cuộc sống này vào mọi khoảnh khắc trong cuộc sống của bạn, một hành trình thay đổi trọn vẹn ở mọi khía cạnh trong cuộc sống tràn ngập niềm vui.</p>\n<p>Không quan trọng bạn là ai, không quan trọng bạn đang ở đâu, không quan trọng tình huống của bạn hiện tại, Phép Màu sẽ tạo ra sự thay đổi hoàn toàn cho cuộc sống của bạn.</p>\n<p>Với hình nội dung ấn tượng và lôi cuốn, <em><strong>"The Magic - Phép màu"</strong></em> sẽ chinh phục mọi độc giả. <strong>Gooda</strong> hy vọng cuốn sách sẽ mang đến những trải nghiệm thật tuyệt, và tự tin đây sẽ là 1 cuốn sách quý trên kệ sách của bạn!</p>\n<p><span style="text-decoration:underline;"><strong>Lưu ý:</strong></span> Đây là cuốn đầu tiên trong bộ sách <strong>The Secret</strong> gồm 4 cuốn (The Magic, The Secret, The Power, Hero). Mời quý độc giả vào Shop <strong>Gooda Officia </strong>để tìm mua các cuốn còn lại trong bộ The Secret!</p>\n<p><img src="https://salt.tikicdn.com/ts/tmp/a0/e5/5f/65b2dc8cb5664910c83bc9418b81e743.jpg" alt="" width="750" height="750"></p>\n<p><strong>QUYỀN LỢI KHÁCH HÀNG KHI MUA SÁCH TẠI SHOP GOODA THƯ VIỆN SÁCH QUÝ:</strong></p>\n<p>1. Đảm bảo 100% sách gốc bản quyền từ NXB</p>\n<p>2. Quy cách đóng gói cẩn thận, trận trọng từng quyển sách</p>\n<p>3. Xử lí đơn đặt hàng nhanh</p>\n<p>4. Chính sách hỗ trợ đổi sách cho khách hàng thuận tiện khi gặp sự cố</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Đừng Chạy Theo Số Đông -  Cuốn Sách Bạn Cần Đọc Trước Khi Quá Muộn',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'Nếu tất cả mọi người ai cũng làm chủ doanh nghiệp, thì ai sẽ đi làm thuê?Tôi.Bởi lúc đó họ sẽ phải đấu giá để có được tôi.Nhưng điều này không bao giờ xảy ra. Bởi ngay từ trong trứng đến lúc mọc cá...',
    price: 107500,
    priceUnDiscount: 110500,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/95/c5/71/f260011660001af960c42d7d2f1c5dc1.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/95/c5/71/f260011660001af960c42d7d2f1c5dc1.jpg',
      'https://salt.tikicdn.com/ts/product/98/0e/6b/d2f0099f405b4450064fa1d79edf3208.jpg',
    ],
    quantity: 100,
    summary:
      '<p>Nếu tất cả mọi người ai cũng làm chủ doanh nghiệp, thì ai sẽ đi làm thuê?</p>\n<p>Tôi.</p>\n<p>Bởi lúc đó họ sẽ phải đấu giá để có được tôi.</p>\n<p>Nhưng điều này không bao giờ xảy ra. Bởi ngay từ trong trứng đến lúc mọc cánh, chúng ta đã được dạy phải làm cho người khác cả đời. Chỉ có 1% được dạy khác.</p>\n<p>Bạn không chạy theo số đông.</p>\n<p>Bạn LÀ số đông.</p>\n<p>Tuy nhiên bạn đừng nhầm lẫn. Cuốn sách này không chỉ nói về vấn đề “làm thuê” hay “làm riêng”. Đây chỉ là một trong những khía cạnh rất nhỏ.</p>\n<p>Cuốn sách này muốn làm nổi bật một hệ tư duy ngầm lớn và khủng khiếp hơn thế mà chúng ta không nhận ra. Một sức hút vô hình nhưng mạnh mẽ.</p>\n<p>Chạy theo số đông.</p>\n<p>Phần lớn mục đích sống và thói quen của bạn không do bạn quyết định. Số đông quyết định hộ bạn mà bạn không nhận ra. Họ “dạy” bạn. Họ “khuyên” bạn. Những lời khuyên và răn dạy có lúc thể hiện qua lời nói và văn bản trực tiếp rõ ràng.</p>\n<p>Nhưng phần lớn nó hàm ý và không rõ ràng. Họ có thể không khuyên bạn trực tiếp. Mà đơn giản hàng triệu người làm theo một thứ hoặc đi theo một con đường nên “chắc chắn nó phải đúng”. Phải không?</p>\n<p>Nếu không đúng tại sao cả xã hội lại làm vậy? Thậm chí “cả Tây cũng làm vậy”?</p>\n<p>Bạn làm theo một cách vô thức. Có một sức hút vô hình từ xã hội, số đông khiến bạn mất kiểm soát nhưng vẫn nghĩ mình đang kiểm soát. “Nó” hút bạn theo con đường mà “nó” chọn cho bạn. “Nó” âm thầm thuyết phục bạn đó là “đam mê” thật sự của bạn. “Mục đích sống” thực sự của bạn. Hoặc nếu không, nếu bạn cưỡng lại, nghi ngờ, “nó” thuyết phục bạn hãy “kiên trì” theo nó. Hứa hẹn với bạn một tương lai tốt đẹp màu hồng vào một ngày nào đó.</p>\n<p>Không xa.</p>\n<p>Giống như sức hút của nam châm. Không màu không mùi không vị. Bạn không nhìn được nó. Không nghe thấy nó. Không ngửi thấy nó. Không sờ thấy nó. Nhưng nó hút. Và hút mạnh. Dù bạn không nhìn thấy.</p>\n<p>Số đông (quần thể) mà chúng ta đang sống là một cục nam châm khổng lồ. Có những “quy luật ngầm” chúng ta tự hiểu với nhau. Bất thành văn. Chúng ta làm theo mà không suy nghĩ. Không đánh giá. Không chút nghi ngờ.</p>\n<p>Để thành công bạn phải học thật giỏi. Tham gia các hoạt động ngoại khóa. Học hết hàng thập kỷ, càng nhiều bằng cấp chứng chỉ càng tốt, sau đó xin việc. Nếu may mắn và được ban ơn bạn sẽ có một công việc dài hạn tại một công ty lớn. Lương cao.</p>\n<p>Tết đến xuân về, họ hàng sum vầy: “Cháu làm ở đâu?”.</p>\n<p>“Cháu làm ở Vietcombank.”</p>\n<p>“Cháu làm ở CenGroup.”</p>\n<p>“Cháu học ở ĐH XYZ ABC.”</p>\n<p>Oai chứ.</p>\n<p>Nhưng một tuần có 7 ngày. Đổi 5 ngày cực nhọc để lấy lại 2 ngày cuối tuần. Bạn vẫn chấp nhận đánh đổi và tự hào.</p>\n<p>Trong suốt nhiều năm.</p>\n<p>Có điều gì đó sai sai.</p>\n<p>Cuộc đời có 80 năm (nếu may mắn). Đánh đổi 65 năm học và cày để đổi lại 10-15 năm “về hưu” vào trại dưỡng lão chơi bingo (nếu may mắn). Còn nếu không may mắn, bạn tự hỏi tiền để làm gì khi sức khỏe và đam mê không còn.</p>\n<p>Phần sau của cuốn sách mình sẽ cho bạn thấy tại sao sự tự hào (pride) về bản chất là thứ cầm tù chúng ta. Không phải thứ giải phóng như bạn vẫn nghĩ.</p>\n<p>***</p>\n<p><strong>Đừng chạy theo số đông</strong> không phải cuốn sách xúi bạn trở thành người kiêu ngạo cực đoan xa lánh số đông.</p>\n<p>Nó là cuốn sách nói lên sự cực đoan kiêu ngạo của số đông và phơi bày hệ thống tư duy công nghiệp (mà số đông nghĩ là hiện đại).</p>\n<p>Và biến bạn trở thành một “số ít” bình thường, hiện đại nhưng khiêm nhường.</p>\n<p>Bởi bạn nhận ra về bản chất, số đông cũng chỉ là nạn nhân.</p>\n<p><strong>- Kiên Trần</strong></p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách - Thao túng tâm lý - 1980BOOKS',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'THÔNG TIN XUẤT BẢN:Tác giả: Shannon Thomas, LCSWDịch giả: Trương Tuấn Giá bìa: 169,000đKích thước khổ:13x20,5Số trang: 328Mã EAN: 8936066692298NXB liên kết:NXB Dân TríSách do Công ty TNHH Văn hóa và T...',
    price: 109850,
    priceUnDiscount: 112850,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/a9/58/93/c0770a8b8a2848da045459658443336e.png',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/a9/58/93/c0770a8b8a2848da045459658443336e.png',
      'https://salt.tikicdn.com/ts/product/f0/a3/77/d1e9f0745ee17a54f5c47cc279bb35e8.jpg',
      'https://salt.tikicdn.com/ts/product/2e/08/d1/2715352f31568fb8d8ad8e01bee667d9.jpg',
      'https://salt.tikicdn.com/ts/product/5b/bf/3a/143247b86cd0bab179731da34a6fdd00.jpg',
    ],
    quantity: 100,
    summary:
      '<p>THÔNG TIN XUẤT BẢN:<br />Tác giả: Shannon Thomas, LCSW<br />Dịch giả: Trương Tuấn <br />Giá bìa: 169,000đ<br />Kích thước khổ:13x20,5<br />Số trang: 328<br />Mã EAN: 8936066692298<br />NXB liên kết:NXB Dân Trí<br />Sách do Công ty TNHH Văn hóa và Truyền thông 1980 BOOKS ấn hành quý 1 năm 2022.<br />--<br />THAO TÚNG TÂM LÝ <br />Trong cuốn “Thao túng tâm lý”, tác giả Shannon Thomas giới thiệu đến độc giả những hiểu biết liên quan đến thao túng tâm lý và lạm dụng tiềm ẩn.<br />“Thao túng tâm lý” là một dạng của lạm dụng tâm lý. Cũng giống như lạm dụng tâm lý, thao túng tâm lý có thể xuất hiện ở bất kỳ môi trường nào, từ bất cứ đối tượng độc hại nào. Đó có thể là bố mẹ ruột, anh chị em ruột, người yêu, vợ hoặc chồng, sếp hay đồng nghiệp… của bạn. Với tính chất bí hiểm, âm thầm gây hại, thao túng, lạm dụng tâm lý làm tổn thương cảm xúc, lòng tự trọng, cuộc sống của mỗi nạn nhân. Những người từng bị lạm dụng tâm lý thường không thể miêu tả rõ ràng điều gì đã xảy ra với mình. Trong nhiều trường hợp, nạn nhân bị thao túng đến mức tự hỏi có phải họ là người có lỗi, thậm chí họ có phải là người độc hại trong mối quan hệ đó.<br />Hành vi của (những) kẻ lạm dụng giống như một trò chơi bí ẩn, tệ hại và lặp đi lặp lại, do một cá nhân hoặc một nhóm người thực hiện với nạn nhân. Những hành vi này được "làm không thật" tài tình đến mức hành vi độc ác của họ diễn ra thường xuyên, nhưng không bị phát hiện. <br />Shannon Thomas giới thiệu những kiến thức cơ bản về đặc điểm, các dạng của lạm dụng tâm lý nói chung, thao túng tâm lý nói riêng, và cung cấp cho người đọc hành trình chữa lành gồm 6 giai đoạn:<br />Giai đoạn 1: Tuyệt vọng<br />Giai đoạn 2: Nhận diện <br />Giai đoạn 3: Thức tỉnh<br />Giai đoạn 4: Những ranh giới <br />Giai đoạn 5: Phục hồi <br />Giai đoạn 6: Duy trì<br />Bằng những kiến thức chuyên sâu và sự thấu hiểu, tác giả sẽ giúp bạn từng bước vượt qua những rắc rối của thao túng tâm lý, lạm dụng tiểm ẩn để có cuộc sống ý nghĩa và lành mạnh hơn.<br />-Thông tin tác giả:<br />Shannon Thomas, là một nhà "quan sát" công tác xã hội y tế được cấp phép hành nghề, và là chủ phòng tư vấn/chuyên gia tư vấn tâm lý chính của phòng tư vấn Southlake Christian (SCC) ở Southlake, bang Texas.<br />SCC từng nhận giải thưởng “Phòng thực hành tư vấn tâm lý tốt nhất” năm 2016 của Living Magazine khu vực Hạt Northeast Tarrant tại Dallas-Fort Worth.<br />Thomas là Trợ giảng chuyên ngành và là thành viên Ủy ban tư vấn của Khoa Công tác xã hội – Trường Đại học Texas Christian.<br />Cách tiếp cận khi tư vấn tâm lý của cô ấy xuất phát từ góc nhìn của một nhà tư vấn tâm lý được cấp phép hành nghề đồng thời từ góc nhìn của một người đi trước, một người sống sót sau khi bị lạm dụng tâm lý.</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách Seneca: Những Bức Thư Đạo Đức – Chủ nghĩa Khắc kỷ trong đời sống',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'GIỚI THIỆU SÁCH CHỦ NGHĨA KHẮC KỶ - SENECA NHỮNG BỨC THƯ ĐẠO ĐỨCChủ Nghĩa Khắc kỷ (Stoicism) là một trường phái triết học cổ đại được sáng lập bởi nhà triết học Zeno xứ Citium vào đầu thế kỷ thứ 3 Tr...',
    price: 149000,
    priceUnDiscount: 152000,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/9d/16/70/96ff593a550354ce055c067d064df37a.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/9d/16/70/96ff593a550354ce055c067d064df37a.jpg',
      'https://salt.tikicdn.com/ts/product/72/e7/e2/75c26e99818a6010ce9074c6229abe2d.jpg',
      'https://salt.tikicdn.com/ts/product/8d/2a/f8/b85f0df22e6d2adcce53cbaf93d06f41.jpg',
      'https://salt.tikicdn.com/ts/product/60/cd/72/54b8a53312480e0fb646633e49dd9c63.jpg',
      'https://salt.tikicdn.com/ts/product/74/53/e0/ad25b1b9dfe0d81cf9cdc203961e631f.jpg',
      'https://salt.tikicdn.com/ts/product/d8/bb/46/f7e27fa1cd26b2a2431e53ae1577406d.jpg',
    ],
    quantity: 100,
    summary:
      '<h2>GIỚI THIỆU SÁCH CHỦ NGHĨA KHẮC KỶ - SENECA NHỮNG BỨC THƯ ĐẠO ĐỨC</h2>\n<p>Chủ Nghĩa Khắc kỷ (Stoicism) là một trường phái triết học cổ đại được sáng lập bởi nhà triết học Zeno xứ Citium vào đầu thế kỷ thứ 3 Trước Công Nguyên. Sau đó trường phái này được kết thừa bởi ba trụ cột thời La Mã là Seneca, hoàng đế Marcus Aurelius và Epictetus.</p>\n<p>Chủ Nghĩa Khắc kỷ được khai sinh với sứ mệnh trui rèn bản lĩnh và tinh thần của con người trước những áp lực và khổ đau trong cuộc sống. Trong một thế giới hiện đại chênh vênh và đầy khủng hoảng: thất nghiệp, dịch bệnh, nỗi đau, cái chết, Chủ nghĩa Khắc kỷ sẽ giúp bạn vững vàng đối mặt và tìm được sự bình thản trong tâm trí (the tranquillity of mind), để không bị "cuốn theo chiều gió" trước vô vàn những cám dỗ và khó khăn của đời sống thường ngày.</p>\n<p>Lucius Annaeus Seneca - một trong ba trụ cột của Chủ nghĩa Khắc Kỷ, đã sử dụng một định dạng văn bản triết học do chính ông sáng tạo ra là các bức thư gần gũi, thân thiện với nhiều đối tượng độc giả để nhằm trả lời cho câu hỏi “làm thế nào một cá nhân có thể đạt được cuộc sống tốt đẹp”. Tính độc đáo của thể loại văn bản này đã được thể hiện trọn vẹn trong tác phẩm nổi tiếng bậc nhất của ông "Moral letters from Seneca to Lucilius”. Tác phẩm này đã được tác giả Andy Lương và đội ngũ Spiderum dịch lại dưới tên “Seneca: Những bức thư đạo đức – Chủ nghĩa Khắc kỷ trong đời sống”.</p>\n<h2>VỀ TÁC GIẢ SENECA - TRỤ CỘT CHỦ NGHĨA KHẮC KỶ</h2>\n<p>Lucius Annaeus Seneca (4 TCN - 65) là một triết gia người La Mã thuộc trường phái Triết học Khắc kỷ và là chính khách, nhà biên kịch, nghệ sĩ hài đương thời, ngoài ra ông còn là một tên tuổi lớn của văn học La Mã. Seneca quan tâm đến việc áp dụng các nguyên tắc đạo đức Khắc Kỷ vào cuộc sống của mình để chữa lành những tổn thương tâm lý. Câu hỏi chi phối các tác phẩm triết học của ông là làm thế nào một cá nhân có thể đạt được cuộc sống tốt đẹp. Các tác phẩm của ông chứa đầy những ví dụ sống động, những ẩn dụ ấn tượng, những câu nói hay và những hiệu ứng âm thanh dứt khoát. Ông biết cách thay đổi giọng điệu, từ cuộc trò chuyện bình thường đến lời cổ vũ mạnh mẽ và sự lên án quyết liệt.</p>\n<h2>AI NÊN ĐỌC CUỐN SÁCH SENECA - CHỦ NGHĨA KHẮC KỶ TRONG ĐỜI SỐNG</h2>\n<p>Những bạn trẻ đang tìm hiểu về triết học, đặc biệt là về Chủ nghĩa Khắc kỷ và phương pháp thực hành triết học trong cuộc sống thường ngày</p>\n<p>Những ai quan tâm tới văn học, lịch sử, nghệ thuật Hy Lạp - La Mã cổ đại để tìm về các tri thức trường tồn qua dòng thời gian của Seneca, Marcus Aurelius, Plato…</p>\n<p>Những ai đang gặp vấn đề với việc phát triển bản thân, các mối quan hệ, sự nghiệp, tình cảm và cần lời khuyên thực sự có ý nghĩa</p>\n<p>Những bạn trẻ muốn trang bị cho mình một tâm thức mạnh mẽ để sẵn sàng đương đầu với thời đại biến đổi khôn cùng.</p>\n<p>_______________________________</p>\n<p>- Tác giả: Lucius Annaeus Seneca</p>\n<p>- Dịch giả: Andy Luong</p>\n<p>- Số trang: 338</p>\n<p>- Ngày xuất bản: 05/05/2021</p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
  {
    name: 'Sách: Thay Đổi Một Suy Nghĩ Thay Đổi cả Cuộc Đời',
    author: 'Author',
    cloudTag: ['simple'],
    description:
      'THAY ĐỔI MỘT SUY NGHĨ THAY ĐỔI MỘT CUỘC ĐỜI Trong cuốn sách này, tác giả đã tổng kết ra những trường hợp điển hình, thông qua đào sâu phân tích và thảo luận để dẫn mọi người cùng tìm kiếm và “nhìn th...',
    price: 120000,
    priceUnDiscount: 123000,
    thumbnail:
      'https://salt.tikicdn.com/ts/product/bc/e4/62/c90d693131214d091e22652d8722c779.jpg',
    category: ['6231ece04793ecd4a7780510', '6270ef3fa5e8884e392b1e44'],
    status: '',
    images: [
      'https://salt.tikicdn.com/ts/product/bc/e4/62/c90d693131214d091e22652d8722c779.jpg',
      'https://salt.tikicdn.com/ts/product/48/d9/6f/3ea5bc5596cb413701514c9db5550a0d.jpg',
      'https://salt.tikicdn.com/ts/product/f4/8e/ad/d8f74ede86d77a8088dd2821a8295ad7.jpg',
      'https://salt.tikicdn.com/ts/product/35/03/28/b7c65983d78b3b9c1c54f5bd9c9c2a66.jpg',
      'https://salt.tikicdn.com/ts/product/7c/24/a4/d7f7cf2f1ce6e5835904594afd832c73.jpg',
      'https://salt.tikicdn.com/ts/product/94/9b/9b/563c62effa431f6556bef9b396649b3e.jpg',
      'https://salt.tikicdn.com/ts/product/47/a1/e0/df3b3ac044c01d21937db14b29206f72.jpg',
      'https://salt.tikicdn.com/ts/product/51/27/82/87df779428ede78d37a3e10e016a9b30.jpg',
      'https://salt.tikicdn.com/ts/product/94/de/47/c90d9148d02f6dd130731a9abd0d063f.jpg',
      'https://salt.tikicdn.com/ts/product/19/9b/55/18a409632c844aa494e7f64e6e7b6c66.jpg',
      'https://salt.tikicdn.com/ts/product/85/dc/05/688ea81cdccc38b01671dae2f588be03.jpg',
      'https://salt.tikicdn.com/ts/product/d3/96/83/c5eacdf4f702fcbb35fbfa3c21258386.jpg',
    ],
    quantity: 100,
    summary:
      '<p class="p1">THAY ĐỔI MỘT SUY NGHĨ THAY ĐỔI MỘT CUỘC ĐỜI </p>\n<p class="p1">Trong cuốn sách này, tác giả đã tổng kết ra những trường hợp điển hình, thông qua đào sâu phân tích và thảo luận để dẫn mọi người cùng tìm kiếm và “nhìn thấy" mô thức sống hiện nay của họ. Những đau khổ của cuộc đời có muôn hình vạn trạng, nhưng mô thức nội tại thì gần như đều giống nhau, ví dụ mô thức bi quan, mô thức đấu tranh nội tâm, mô thức đau khổ, mô thức giả vờ bận rộn, mô thức tự cao tự đại, mô thức chỉ trích, mô thức làm nạn nhân, mô thức thao túng, mô thức sợ hãi, mô thức la â Trong những trường hợp sinh động này, bạn có thể nhìn thấy bóng dáng của mình, đồng thời phát hiện ra mô thức sống mà mình đang vận hành.  </p>\n<p class="p1">Chỉ khi nhìn thấy mô thức sống của chính mình, con người mới tự nhiên thay đổi. Tác giả gọi quá trình thay đổi này là “nâng cấp sinh mệnh". </p>\n<p class="p1">Bản thân tác giả cũng đã từng trải nghiệm việc đi trên con đường ấy, vì vậy, có lẽ tác giả biết còn rất nhiều tâm hồn khác nhau đang trải qua những đau khổ vô minh giống như ông và cần được đánh thức! Thông qua cuốn sách này, có thể giúp cuộc đời của bạn đọc trở nên tốt đẹp hơn. </p>\n<p class="p1">Cuộc đời của mỗi chúng ta đều có thể vô cùng đẹp đẽ, và cũng có thể tầm thường vô vị, mấu chốt là ở chỗ chúng ta có thể nhìn thấy và cảm nhận mô thức sống của mình đồng thời không ngừng nỗ lực để theo đuổi một cuộc đời tốt đẹp hơn hay không. Vì vậy, khi bạn đang than thở cuộc đời không như ý, oán trách bất công, hãy tự hỏi bản thân rằng: Mình đã tạo ra tất cả mọi thứ ngày hôm nay như thế nào? Loại mô thức nội tại nào của mình khiến thế giới đối xử với mình như vậy.  </p>\n<p class="p1">Hãy mở cuốn sách này ra, có lẽ trong đây có câu trả lời mà bạn cần! </p><p>Giá sản phẩm trên Tiki đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....</p>',
    publishers: ['625a89ce96200f1ddd041df1', '625a89ce96200f1ddd041df0'],
    isCombo: false,
    books: [],
  },
];
